import ResourceAwareScheduler from '../../src/resource-aware/ResourceAwareScheduler.js';
import DVFSController from '../../src/resource-aware/DVFSController.js';

/**
 * Integration Test: ResourceAwareScheduler and DVFSController
 *
 * This test simulates a supervisor process that manages both the task scheduler and
 * the DVFS controller. It verifies that the DVFS controller correctly adapts to the
 * CPU load generated by tasks being run by the scheduler.
 */
describe('ResourceAwareScheduler and DVFSController Integration', () => {
  it('should cause the DVFS controller to scale up under high load and down under low load', () => {
    // 1. Arrange: Set up the components and initial state
    const budgets = { cpu: 1000, energy: 1e6, memory: 1e6 };
    const scheduler = new ResourceAwareScheduler(budgets);
    const controller = new DVFSController();

    // Initially, the controller should be in a balanced state
    expect(controller.getCurrentState().name).toBe('Balanced');

    // Define a set of high-load tasks
    const highLoadTasks = Array.from({ length: 10 }, (_, i) => ({
      name: `High CPU Task ${i}`,
      operations: 8e9, // High CPU cost
      value: 10,
      execute: () => 'complete',
    }));

    // Define a single low-load task
    const lowLoadTask = {
      name: 'Low CPU Task',
      operations: 1e8, // Low CPU cost
      value: 5,
      execute: () => 'complete',
    };

    // 2. Act: Simulate a period of high load by repeatedly telling the controller the load is high
    console.log('--- Simulating High Load ---');
    for (let i = 0; i < 5; i++) {
        controller.adapt({
            loadPercent: 95, // Simulate 95% instantaneous load
            batteryPercent: 100,
            tempCelsius: 70,
        });
    }

    // 3. Assert: The controller should have scaled up
    console.log(`Final state after high load: ${controller.getCurrentState().name}`);
    expect(['Performance', 'Turbo']).toContain(controller.getCurrentState().name);

    // 2. Act: Simulate a period of low load
    console.log('--- Simulating Low Load ---');
    for (let i = 0; i < 5; i++) {
        controller.adapt({
            loadPercent: 15, // Simulate 15% instantaneous load
            batteryPercent: 100,
            tempCelsius: 50,
        });
    }

    // 3. Assert: The controller should have scaled down
    console.log(`Final state after low load: ${controller.getCurrentState().name}`);
    expect(['Eco', 'Low', 'Balanced']).toContain(controller.getCurrentState().name);
  });
});
